### ISSUE TITLE
Download code from external sources, possibly gists

### ISSUE THREAD

**Issue by skade** [moztn/pRust#1]
For rust-handson, which is a multi-lingual slidedeck for Rust, we currently copy code into both translations. It would be easier if we could share the code in some way, either by downloading the example from the location of the slidedeck or maybe loading them from a gist.

It could, for example, look like this:

```
<pre><code data-source="src/hello_world.rs" data-trim class="hljs rust"></code></pre>
```

The tracking issue on the other side is this:
https://github.com/chikoski/rust-handson/issues/7

**Comment by bashz** [comment]
On it, on both sides.

**Comment by bashz** [comment]
PR on chikoski/rust-handson#7 , will add almost the same code here.
